### ISSUE TITLE
Titel no clickable

### ISSUE THREAD

**Issue by Bobbll** [storj/awesome-storj#54]
![Screenshot 2023-12-14 220658](https://github.com/storj/awesome-storj/assets/7007720/4cdd5824-e2a8-4f6f-a68b-3451eed66483)
All Title cant click always come this report. Title Node, Satelite and Success Audit.... is ok. Can you help me

**Comment by elek** [comment]
Not sure what is the problem exactly. Looks like it's related to one of the Storj projects and not the link list.

I would suggest to share the problem on the forum: https://forum.storj.io/
